"""
Hermes Agent — KotipotiBot
===========================
Nightly analysis agent that reads Freqtrade trade logs,
computes a daily P&L summary, and sends a Telegram report.

Runs on a schedule (default: 23:55 every day).
"""

import os
import json
import glob
import schedule
import time
import requests
from datetime import datetime, timedelta
from pathlib import Path


# ---- Config ----
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")
LOG_DIR = Path("/freqtrade/user_data/logs")
DATA_DIR = Path("/freqtrade/user_data/data")
REPORT_TIME = "23:55"  # 24h time, Pi local timezone


# ---- Telegram helpers ----
def send_telegram(message: str) -> bool:
    """Send a message to Telegram. Returns True on success."""
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("[Hermes] WARNING: Telegram token/chat_id not set. Skipping send.")
        return False
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message,
        "parse_mode": "Markdown",
    }
    try:
        resp = requests.post(url, json=payload, timeout=10)
        resp.raise_for_status()
        print(f"[Hermes] Telegram message sent OK ({len(message)} chars)")
        return True
    except Exception as e:
        print(f"[Hermes] Failed to send Telegram message: {e}")
        return False


# ---- Log parsing ----
def parse_trade_log() -> dict:
    """
    Read the Freqtrade log file and extract today's trade events.
    Returns a dict with summary stats.
    """
    log_file = LOG_DIR / "freqtrade.log"
    today = datetime.utcnow().date()
    yesterday = today - timedelta(days=1)

    stats = {
        "date": str(yesterday),
        "entries": 0,
        "exits": 0,
        "wins": 0,
        "losses": 0,
        "total_profit_pct": 0.0,
        "errors": 0,
        "raw_lines": [],
    }

    if not log_file.exists():
        print(f"[Hermes] Log file not found: {log_file}")
        return stats

    with open(log_file, "r") as f:
        for line in f:
            # Only look at yesterday's entries
            if str(yesterday) not in line:
                continue
            stats["raw_lines"].append(line.strip())
            lower = line.lower()

            if "entering short" in lower or "enter short" in lower:
                stats["entries"] += 1
            if "exiting short" in lower or "exit short" in lower or "closed short" in lower:
                stats["exits"] += 1
            if "profit" in lower:
                # Try to extract profit percentage
                try:
                    idx = lower.index("profit")
                    snippet = line[idx:idx+30]
                    nums = [
                        float(x.replace("%", "").replace(",", ""))
                        for x in snippet.split()
                        if x.replace(".", "").replace("-", "").replace("%", "").isdigit()
                    ]
                    if nums:
                        pct = nums[0]
                        stats["total_profit_pct"] += pct
                        if pct >= 0:
                            stats["wins"] += 1
                        else:
                            stats["losses"] += 1
                except Exception:
                    pass
            if "error" in lower or "exception" in lower:
                stats["errors"] += 1

    return stats


# ---- Report builder ----
def build_report(stats: dict) -> str:
    """Format the nightly report message."""
    win_rate = (
        round(stats["wins"] / stats["exits"] * 100, 1)
        if stats["exits"] > 0
        else 0
    )
    profit_emoji = "🟢" if stats["total_profit_pct"] >= 0 else "🔴"

    report = f"""🤖 *KotipotiBot — Nightly Report*
📅 Date: `{stats['date']}`

📊 *Trade Summary*
• Entries (shorts): `{stats['entries']}`
• Exits: `{stats['exits']}`
• Wins / Losses: `{stats['wins']} / {stats['losses']}`
• Win Rate: `{win_rate}%`
• Est. Total Profit: {profit_emoji} `{stats['total_profit_pct']:.2f}%`

⚠️ *Errors logged*: `{stats['errors']}`

_Report generated by Hermes at {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC_
"""
    return report


# ---- Main job ----
def nightly_report():
    print(f"[Hermes] Running nightly report at {datetime.utcnow().isoformat()}")
    stats = parse_trade_log()
    report = build_report(stats)
    print(report)
    send_telegram(report)


# ---- Scheduler ----
def main():
    print(f"[Hermes] Agent started. Nightly report scheduled at {REPORT_TIME}.")
    send_telegram(
        f"🚀 *Hermes Agent started*\nNightly reports scheduled at `{REPORT_TIME}` UTC."
    )
    schedule.every().day.at(REPORT_TIME).do(nightly_report)

    # Also run once on startup if it's past report time (useful after restarts)
    now = datetime.utcnow().strftime("%H:%M")
    if now >= REPORT_TIME:
        print("[Hermes] Past report time — running report now.")
        nightly_report()

    while True:
        schedule.run_pending()
        time.sleep(30)


if __name__ == "__main__":
    main()
